package com.app;

public enum AppEvent {
	ONLINE_CHANGED, 
	MEMO_STATE_CHANGED,
	METER_STATE_CHANGED,
	OVERLIMIT_STATE_CHANGED,
	REMINDER_STATE_CHANGED,
	SCREENSHOT_CREATED, 
	SCREENSHOT_FAILS,
	SERVER_FAILS, 
	SETTINGS_UPDATED,
	STATISTIC_UPDATED,
	EXIT
}
